source('/Rscripts/install_packages_function.R')

# utility packages
packages_to_install <- c(
  'remotes',
  'devtools',
  'tidyverse',
  'jalvesaq/colorout',
  'concaveman',
  'corrr',
  'dendextend',
  'densityClust',
  'xiaodaigh/disk.frame',
  'DT',
  'fastcluster',
  'FlowSOM',
  'foreign',
  'future.apply',
  'gam',
  'golem',
  'h2o',
  'hdf5r',
  'intrinsicDimension',
  'lwgeom',
  'magrittr',
  'phylogram',
  'pryr',
  'renv',
  'reshape2',
  'reticulate',
  'rgdal',
  'roxygen2',
  'Rtsne',
  'scales',
  'shiny',
  'shinydashboard',
  'shinyjs',
  'shinythemes',
  'sf',
  'statsbomb/StatsBombR',
  'stringi',
  'tensorflow',
  'tsne',
  'krlmlr/ulimit',
  'umap',
  'uwot',
  'XML',
  'xml2'
)

install_packages(packages_to_install)

